// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

export type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *homepage → Hero Section*
 */
export interface HomepageDocumentDataHeroSectionItem {
  /**
   * Title field in *homepage → Hero Section*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Resilience for all
   * - **API ID Path**: homepage.hero_section[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *homepage → Hero Section*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Education for all, igniting hope
   * - **API ID Path**: homepage.hero_section[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField;
}

/**
 * Item in *homepage → Section grid*
 */
export interface HomepageDocumentDataSectionGridItem {
  /**
   * Title field in *homepage → Section grid*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Community Development Programs
   * - **API ID Path**: homepage.section_grid[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *homepage → Section grid*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Engage in our holistic community development initiatives. From infrastructure projects to educational programs, we work collaboratively to foster sustainable growth and empowerment.
   * - **API ID Path**: homepage.section_grid[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *homepage → About Us*
 */
export interface HomepageDocumentDataAboutUsItem {
  /**
   * Title field in *homepage → About Us*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Empowering Lives, Creating Impact
   * - **API ID Path**: homepage.about_us[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *homepage → About Us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Future Resilience and Development Foundation (FRAD Foundation) is a registered Non-profit organization with the corporate affairs commission (CAC) with CAC No CAC/IT/NO/139393 in 2019 in accordance with the Nigerian Law with office address at Suit B87, Mohammed Goni, Complex, Maiduguri Borno state, Nigeria.
   * - **API ID Path**: homepage.about_us[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *homepage → Features*
 */
export interface HomepageDocumentDataFeaturesItem {
  /**
   * Title field in *homepage → Features*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Become a volunteer
   * - **API ID Path**: homepage.features[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * text field in *homepage → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Join FRAD Foundation as a volunteer, contributing to community development, humanitarian aid, and education in Maiduguri, Nigeria. Your commitment helps foster sustainable growth and empowerment, creating positive change.
   * - **API ID Path**: homepage.features[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *homepage → Slice zone → Hero Section → Primary*
 */
export interface HomepageDocumentDataBodyHeroSectionSlicePrimary {
  /**
   * Call to action field in *homepage → Slice zone → Hero Section → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call To Action
   * - **API ID Path**: homepage.body[].hero_section.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action: prismic.LinkField;
}

/**
 * Slice for *homepage → Slice zone*
 */
export type HomepageDocumentDataBodyHeroSectionSlice = prismic.Slice<
  "hero_section",
  Simplify<HomepageDocumentDataBodyHeroSectionSlicePrimary>,
  never
>;

type HomepageDocumentDataBodySlice = HomepageDocumentDataBodyHeroSectionSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Hero Section field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero_section: prismic.GroupField<
    Simplify<HomepageDocumentDataHeroSectionItem>
  >;

  /**
   * Section Two Heading field in *homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Empowering Lives, Creating Impact
   * - **API ID Path**: homepage.section_two_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_two_heading: prismic.TitleField;

  /**
   * Section grid field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.section_grid[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section_grid: prismic.GroupField<
    Simplify<HomepageDocumentDataSectionGridItem>
  >;

  /**
   * About Us field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.about_us[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  about_us: prismic.GroupField<Simplify<HomepageDocumentDataAboutUsItem>>;

  /**
   * Features field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.features[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<Simplify<HomepageDocumentDataFeaturesItem>>;

  /**
   * Slice zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Index Page → Hero Section*
 */
export interface IndexPageDocumentDataHeroSectionItem {
  /**
   * Title field in *Index Page → Hero Section*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Resilience for all
   * - **API ID Path**: index_page.hero_section[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Index Page → Hero Section*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Education for all, igniting hope
   * - **API ID Path**: index_page.hero_section[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField;
}

/**
 * Item in *Index Page → Section grid*
 */
export interface IndexPageDocumentDataSectionGridItem {
  /**
   * Title field in *Index Page → Section grid*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Community Development Programs
   * - **API ID Path**: index_page.section_grid[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *Index Page → Section grid*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Engage in our holistic community development initiatives. From infrastructure projects to educational programs, we work collaboratively to foster sustainable growth and empowerment.
   * - **API ID Path**: index_page.section_grid[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Index Page → About Us*
 */
export interface IndexPageDocumentDataAboutUsItem {
  /**
   * Title field in *Index Page → About Us*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Empowering Lives, Creating Impact
   * - **API ID Path**: index_page.about_us[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *Index Page → About Us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Future Resilience and Development Foundation (FRAD Foundation) is a registered Non-profit organization with the corporate affairs commission (CAC) with CAC No CAC/IT/NO/139393 in 2019 in accordance with the Nigerian Law with office address at Suit B87, Mohammed Goni, Complex, Maiduguri Borno state, Nigeria.
   * - **API ID Path**: index_page.about_us[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Index Page → Features*
 */
export interface IndexPageDocumentDataFeaturesItem {
  /**
   * Title field in *Index Page → Features*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Become a volunteer
   * - **API ID Path**: index_page.features[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * text field in *Index Page → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Join FRAD Foundation as a volunteer, contributing to community development, humanitarian aid, and education in Maiduguri, Nigeria. Your commitment helps foster sustainable growth and empowerment, creating positive change.
   * - **API ID Path**: index_page.features[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Index Page → Slice zone → Hero Section → Primary*
 */
export interface IndexPageDocumentDataBodyHeroSectionSlicePrimary {
  /**
   * Call to action field in *Index Page → Slice zone → Hero Section → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call To Action
   * - **API ID Path**: index_page.body[].hero_section.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action: prismic.LinkField;
}

/**
 * Slice for *Index Page → Slice zone*
 */
export type IndexPageDocumentDataBodyHeroSectionSlice = prismic.Slice<
  "hero_section",
  Simplify<IndexPageDocumentDataBodyHeroSectionSlicePrimary>,
  never
>;

type IndexPageDocumentDataBodySlice = IndexPageDocumentDataBodyHeroSectionSlice;

/**
 * Content for Index Page documents
 */
interface IndexPageDocumentData {
  /**
   * Hero Section field in *Index Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.hero_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero_section: prismic.GroupField<
    Simplify<IndexPageDocumentDataHeroSectionItem>
  >;

  /**
   * Section Two Heading field in *Index Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Empowering Lives, Creating Impact
   * - **API ID Path**: index_page.section_two_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_two_heading: prismic.TitleField;

  /**
   * Section grid field in *Index Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.section_grid[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section_grid: prismic.GroupField<
    Simplify<IndexPageDocumentDataSectionGridItem>
  >;

  /**
   * About Us field in *Index Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.about_us[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  about_us: prismic.GroupField<Simplify<IndexPageDocumentDataAboutUsItem>>;

  /**
   * Features field in *Index Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.features[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<Simplify<IndexPageDocumentDataFeaturesItem>>;

  /**
   * Slice zone field in *Index Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<IndexPageDocumentDataBodySlice>;
}

/**
 * Index Page document from Prismic
 *
 * - **API ID**: `index_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IndexPageDocumentData>,
    "index_page",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument | IndexPageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataHeroSectionItem,
      HomepageDocumentDataSectionGridItem,
      HomepageDocumentDataAboutUsItem,
      HomepageDocumentDataFeaturesItem,
      HomepageDocumentDataBodyHeroSectionSlicePrimary,
      HomepageDocumentDataBodySlice,
      IndexPageDocument,
      IndexPageDocumentData,
      IndexPageDocumentDataHeroSectionItem,
      IndexPageDocumentDataSectionGridItem,
      IndexPageDocumentDataAboutUsItem,
      IndexPageDocumentDataFeaturesItem,
      IndexPageDocumentDataBodyHeroSectionSlicePrimary,
      IndexPageDocumentDataBodySlice,
      AllDocumentTypes,
    };
  }
}
