import {
  Menu,
  Search,
  Phone,
  Mail,
  MapPin,
  Share2,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  Plus,
  Minus,
  ChevronRight,
  CircleFadingPlus,
} from "lucide-react";

export const LucideIcons = {
  circleFadingPlus: CircleFadingPlus,
  chevronRight: ChevronRight,
  hamburger: Menu,
  search: Search,
  telephone: Phone,
  mail: Mail,
  mapPin: MapPin,
  share: Share2,
  facebook: Facebook,
  twitter: Twitter,
  linkedIn: Linkedin,
  instagram: Instagram,
  plus: Plus,
  minus: Minus,
};
